---
title: "Friday"
subtitle: "Services"
logo: "../assets/icons/friday_logo.jpeg"

header: false
footer: '<p>© Fem Gandhi, 2022 </p>' # Set false to hide.

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper_friday.jpeg"
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper_friday_dark.jpeg"

services:
  - name: "//GitHub"
    icon: "fas fa-github"
    items:
      - name: "Friday"
        logo: "assets/icons/png/github.png" # Change github.png to the name of your own custom icon!
        subtitle: "Repo"
        tag: "github"
        tagstyle: "is-primary" # This will display the is-primary color! Try changing it to; is-link, is-info, is-success, is-warning or is-danger!
        url: "https://github.com/femGandhi/Friday"
        target: "_blank"

  - name: "//Jellyfin"
    icon: "fas fa-tv-alt"
    items:
      - name: "Jellyfin"
        logo: "assets/icons/png/jellyfin.png"
        subtitle: "Lets Watch Stuff"
        tag: "Stream"
        tagstyle: "is-primary"
        url: "friday.local:8096"
        target: "_blank"
